first commit

diff --git a/.github/workflows/deploy-docker-image.yml b/.github/workflows/deploy-docker-image.yml
--- a/.github/workflows/deploy-docker-image.yml
+++ b/.github/workflows/deploy-docker-image.yml
@@ -42,21 +42,21 @@ jobs:
           # Copiar el manifiesto de despliegue al servidor EC2
           echo "${{ vars.DEPLOYMENT_MANIFEST }}" > /tmp/deployment.yaml
           echo "${{ vars.SERVICE_MANIFEST }}" > /tmp/service.yaml
+          echo "${{ vars.CONFIG_MAP_PROMETHEUS }}" > /tmp/configmap.yaml
           echo "${{ vars.PROMETHEUS_MANIFEST }}" > /tmp/prometheus.yaml
           echo "${{ vars.GRAFANA_MANIFEST }}" > /tmp/grafana.yaml
 
           # Comprobar el acceso a kubectl
           kubectl config current-context || { echo "Error: kubectl no está configurado."; exit 1; }
       
-          # Aplicar el manifiesto del Deployment en Kubernetes
           kubectl apply -f /tmp/deployment.yaml || { echo "Error: Falló el apply del deployment."; exit 1; }
 
-          # Aplicar el manifiesto del Service en Kubernetes
-          kubectl apply -f /tmp/service.yaml || { echo "Error: Falló el apply del service."; exit 1; }
+          kubectl apply -f /tmp/configmap.yaml || { echo "Error: Falló el apply del Configmap."; exit 1; }          
+          kubectl rollout status deployment/configmap || { echo "Error: El Configmap falló."; exit 1; }
           
-          # Comprobar el estado del despliegue
-          kubectl rollout status deployment/my-app-deployment || { echo "Error: El despliegue falló."; exit 1; }
-          # Aplicar el manifiesto de Prometheus
+          kubectl apply -f /tmp/prometheus.yaml || { echo "Error: Falló el apply de Prometheus."; exit 1; }
+          kubectl rollout status deployment/prometheus || { echo "Error: El despliegue de Prometheus falló."; exit 1; }
+
           kubectl apply -f /tmp/prometheus.yaml || { echo "Error: Falló el apply de Prometheus."; exit 1; }
           kubectl rollout status deployment/prometheus || { echo "Error: El despliegue de Prometheus falló."; exit 1; }
 
